r"""DAG plan loading, validation, and execution.

A Plan is a directed acyclic graph of prompt nodes. Each node may depend on
other nodes; its prompt may reference upstream node results via
`{{node_id.result}}` placeholders, substituted right before the node is
submitted to the SLM queue.

Status lifecycle per node:
    pending  -> queued  -> running  -> done   (success path)
                                    \-> error (worker failed)

A PlanRunner walks the DAG in a background thread, submitting ready nodes
to a Dispatcher, polling for results, and unlocking dependents.
"""
from __future__ import annotations

import hashlib
import json
import re
import threading
import time
import uuid
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from server import Dispatcher


_PLACEHOLDER = re.compile(r"\{\{\s*(\w+)\.result\s*\}\}")


def _record_run_metric(run: "PlanRun", terminal_status: str) -> None:
    """Best-effort write to the SlowAndSweet SQLite metrics.

    Lazy-imported so the queue keeps working when the `slowandsweet` wheel
    isn't installed. Swallows all errors — metrics must never take down a
    plan run.
    """
    try:
        from slowandsweet import state  # type: ignore
    except ImportError:
        import sys as _sys
        repo_pkg = Path(__file__).resolve().parent.parent / "slowandsweet"
        if (repo_pkg / "slowandsweet" / "state.py").exists():
            _sys.path.insert(0, str(repo_pkg))
        try:
            from slowandsweet import state  # type: ignore
        except Exception:  # noqa: BLE001
            return
    except Exception:  # noqa: BLE001
        return
    try:
        slm_tokens_out = sum(
            (n.get("eval_count") or 0) for n in run.nodes.values()
        )
        wall_ms = None
        if run.finished_at is not None:
            wall_ms = int((run.finished_at - run.created_at) * 1000)
        # Counterfactual: what would it have cost had the frontier model
        # produced these leaves itself, serially, in one response? Output
        # volume is assumed comparable (SLMs handle mechanical rewrites
        # without inflation), and 25 ms/token approximates a frontier
        # model's steady-state output rate (~40 tok/s).
        estimated_solo_tokens = slm_tokens_out or None
        estimated_solo_wall_ms = (
            slm_tokens_out * 25 if slm_tokens_out else None
        )
        status = "delegated" if terminal_status == "done" else "failed"
        state.record_call(
            call_id=run.run_id,
            status=status,
            slm_tokens_out=slm_tokens_out or None,
            wall_ms=wall_ms,
            estimated_solo_tokens=estimated_solo_tokens,
            estimated_solo_wall_ms=estimated_solo_wall_ms,
        )
    except Exception:  # noqa: BLE001
        return

    try:
        _report_router_feedback(
            run,
            slm_tokens_out=slm_tokens_out,
            wall_ms=wall_ms,
            estimated_solo_tokens=estimated_solo_tokens,
            estimated_solo_wall_ms=estimated_solo_wall_ms,
        )
    except Exception:  # noqa: BLE001
        return


def _router_prompt_for(run: "PlanRun") -> str:
    # `plan.description` is what choose_arm() sees when the plan is dispatched
    # -- it's the user-facing summary that stands in for "what would have been
    # sent solo". Fall back to the first node's prompt template if empty.
    desc = (run.plan.description or "").strip()
    if desc:
        return desc
    first = run.plan.nodes[0] if run.plan.nodes else None
    return (first or {}).get("prompt", "")


_TIKTOKEN_ENC: object | None = None
_TIKTOKEN_TRIED = False


def _count_tokens(text: str) -> int:
    """cl100k_base tokens if tiktoken is installed; whitespace-split otherwise."""
    global _TIKTOKEN_ENC, _TIKTOKEN_TRIED
    if not text:
        return 0
    if not _TIKTOKEN_TRIED:
        _TIKTOKEN_TRIED = True
        try:
            import tiktoken  # type: ignore
            _TIKTOKEN_ENC = tiktoken.get_encoding("cl100k_base")
        except Exception:  # noqa: BLE001
            _TIKTOKEN_ENC = None
    if _TIKTOKEN_ENC is not None:
        return len(_TIKTOKEN_ENC.encode(text))  # type: ignore[attr-defined]
    return len(text.split())


# Small wrapper that stands in for the "compose from SLM outputs" instruction a
# real caller would prepend to the terminal-node results. Kept static so the
# feedback record's composer_tokens_actual is deterministic across runs.
_COMPOSER_WRAPPER = (
    "You are producing the final answer for the user. The outputs below were "
    "generated by local SLMs handling the mechanical sub-tasks. Compose them "
    "into a single response.\n\n"
)


def _composer_prompt_approx(run: "PlanRun") -> str:
    """Approximate the composer prompt: wrapper + terminal-node results."""
    depended_on: set[str] = set()
    for n in run.plan.nodes:
        for dep in n.get("depends_on", []):
            depended_on.add(dep)
    terminal_ids = [n["id"] for n in run.plan.nodes if n["id"] not in depended_on]
    parts = [_COMPOSER_WRAPPER]
    for nid in terminal_ids:
        result = (run.nodes.get(nid) or {}).get("result", "") or ""
        parts.append(f"[{nid}]\n{result}")
    return "\n\n".join(parts)


def _report_router_feedback(
    run: "PlanRun",
    slm_tokens_out: int,
    wall_ms: int | None,
    estimated_solo_tokens: int | None,
    estimated_solo_wall_ms: int | None,
) -> None:
    import os
    if not os.environ.get("SLM_ROUTER_URL"):
        return

    import router as _router
    prompt = _router_prompt_for(run)
    if not prompt:
        return

    stashed = _router.get_stashed_decision(prompt)
    if not stashed:
        return

    explore = _router._load_explore_module()
    if explore is None:
        return

    # Router cost model is about INPUT tokens (what Claude ingests), not the
    # counterfactual output volume estimated_solo_tokens carries for SQLite.
    # Solo path: user sends plan.description; mixture path: composer sees a
    # wrapper + terminal-node results. Both tokenized with cl100k_base.
    solo_input_tok = _count_tokens(prompt)
    composer_input_tok = _count_tokens(_composer_prompt_approx(run))

    if solo_input_tok > 0:
        observed_reduction_pct = (
            (solo_input_tok - composer_input_tok) / solo_input_tok * 100.0
        )
    else:
        observed_reduction_pct = None

    wall_ms_saved = None
    if estimated_solo_wall_ms is not None and wall_ms is not None:
        wall_ms_saved = estimated_solo_wall_ms - wall_ms

    prompt_hash = "sha256:" + hashlib.sha256(prompt.encode("utf-8")).hexdigest()
    # prompt_text is what train.py embeds. Design §4.2 elides it for brevity;
    # add it back so the training pipeline has something to feed MiniLM.
    record = {
        "decision_id": stashed.get("decision_id"),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "prompt_hash": prompt_hash,
        "prompt_text": prompt,
        "prompt_len_tok": _count_tokens(prompt),
        "decision_made": "mixture",
        "policy": stashed.get("policy"),
        "head_version": stashed.get("head_version"),
        "outcome": {
            "solo_tokens_estimated": solo_input_tok,
            "composer_tokens_actual": composer_input_tok,
            "observed_reduction_pct": observed_reduction_pct,
            "wall_ms_slm_dag": wall_ms,
            "wall_ms_saved_vs_solo": wall_ms_saved,
            "quality_verdict": None,
            "quality_source": "none",
        },
    }
    try:
        explore.report_feedback(record)
    except Exception:  # noqa: BLE001
        return


class PlanError(ValueError):
    pass


class Plan:
    def __init__(self, plan_id: str, description: str, nodes: list[dict]):
        self.plan_id = plan_id
        self.description = description
        self.nodes = nodes
        self._validate()

    @classmethod
    def from_file(cls, path: Path) -> "Plan":
        data = json.loads(path.read_text())
        return cls(
            plan_id=data.get("plan_id") or path.stem,
            description=data.get("description", ""),
            nodes=data["nodes"],
        )

    @classmethod
    def from_dict(cls, data: dict) -> "Plan":
        return cls(
            plan_id=data.get("plan_id", "inline"),
            description=data.get("description", ""),
            nodes=data["nodes"],
        )

    def _validate(self) -> None:
        if not self.nodes:
            raise PlanError("plan has no nodes")
        ids = [n["id"] for n in self.nodes]
        if len(set(ids)) != len(ids):
            raise PlanError("duplicate node ids")
        id_set = set(ids)
        for n in self.nodes:
            if "prompt" not in n or not n["prompt"]:
                raise PlanError(f"node {n['id']} missing prompt")
            for dep in n.get("depends_on", []):
                if dep not in id_set:
                    raise PlanError(f"node {n['id']} depends on unknown node {dep}")
            refs = set(_PLACEHOLDER.findall(n["prompt"]))
            declared = set(n.get("depends_on", []))
            stray = refs - declared
            if stray:
                raise PlanError(
                    f"node {n['id']} prompt references {sorted(stray)} "
                    f"but they are not in depends_on"
                )
        # Cycle detection via topological sort (Kahn's algorithm).
        indeg = {n["id"]: len(n.get("depends_on", [])) for n in self.nodes}
        children: dict[str, list[str]] = {n["id"]: [] for n in self.nodes}
        for n in self.nodes:
            for dep in n.get("depends_on", []):
                children[dep].append(n["id"])
        queue = [nid for nid, d in indeg.items() if d == 0]
        seen = 0
        while queue:
            nid = queue.pop()
            seen += 1
            for c in children[nid]:
                indeg[c] -= 1
                if indeg[c] == 0:
                    queue.append(c)
        if seen != len(self.nodes):
            raise PlanError("plan contains a cycle")


class PlanRun:
    """Mutable state for one execution of a Plan."""

    def __init__(self, plan: Plan):
        self.run_id = uuid.uuid4().hex[:12]
        self.plan = plan
        self.created_at = time.time()
        self.nodes: dict[str, dict] = {
            n["id"]: {
                "id": n["id"],
                "prompt_template": n["prompt"],
                "depends_on": list(n.get("depends_on", [])),
                "status": "pending",
            }
            for n in plan.nodes
        }
        self.lock = threading.Lock()
        self.status = "running"  # running | done | error
        self.finished_at: float | None = None

    def snapshot(self) -> dict:
        with self.lock:
            return {
                "run_id": self.run_id,
                "plan_id": self.plan.plan_id,
                "description": self.plan.description,
                "created_at": self.created_at,
                "finished_at": self.finished_at,
                "status": self.status,
                "node_order": [n["id"] for n in self.plan.nodes],
                "nodes": {nid: dict(self.nodes[nid]) for nid in self.nodes},
            }


class PlanRunner:
    """Drives a PlanRun against a Dispatcher in a background thread."""

    def __init__(self, run: PlanRun, dispatcher: "Dispatcher"):
        self.run = run
        self.dispatcher = dispatcher
        self.thread = threading.Thread(
            target=self._loop, daemon=True, name=f"planrun-{run.run_id}"
        )

    def start(self) -> None:
        self.thread.start()

    def _ready_node_ids(self) -> list[str]:
        out = []
        for nid, n in self.run.nodes.items():
            if n["status"] != "pending":
                continue
            if all(self.run.nodes[d]["status"] == "done" for d in n["depends_on"]):
                out.append(nid)
        return out

    def _resolve(self, template: str) -> str:
        def sub(m):
            return self.run.nodes[m.group(1)].get("result", "")
        return _PLACEHOLDER.sub(sub, template)

    def _loop(self) -> None:
        in_flight: dict[str, str] = {}  # node_id -> dispatcher task_id

        while True:
            # 1. Enqueue any newly-ready nodes.
            with self.run.lock:
                for nid in self._ready_node_ids():
                    node = self.run.nodes[nid]
                    prompt = self._resolve(node["prompt_template"])
                    task_id, model = self.dispatcher.submit(prompt)
                    node.update({
                        "status": "queued",
                        "task_id": task_id,
                        "model": model,
                        "prompt": prompt,
                        "submitted_at": time.time(),
                    })
                    in_flight[nid] = task_id

            # 2. Mirror task state into node state.
            for nid, tid in list(in_flight.items()):
                r = self.dispatcher.get(tid)
                if r is None:
                    continue
                with self.run.lock:
                    node = self.run.nodes[nid]
                    if r["status"] == "running" and node["status"] == "queued":
                        node["status"] = "running"
                        node["started_at"] = r.get("started_at")
                        node["worker"] = r.get("worker")
                    if r["status"] == "done":
                        node["status"] = "done"
                        node["started_at"] = node.get("started_at") or r.get("started_at")
                        node["worker"] = node.get("worker") or r.get("worker")
                        node["result"] = r.get("result", "")
                        node["eval_count"] = r.get("eval_count")
                        node["finished_at"] = r.get("finished_at")
                        del in_flight[nid]
                    elif r["status"] == "error":
                        node["status"] = "error"
                        node["error"] = r.get("error")
                        node["finished_at"] = r.get("finished_at")
                        del in_flight[nid]

            # 3. Termination check.
            terminal: str | None = None
            with self.run.lock:
                statuses = [n["status"] for n in self.run.nodes.values()]
                if all(s == "done" for s in statuses):
                    self.run.status = "done"
                    self.run.finished_at = time.time()
                    terminal = "done"
                # No more progress possible if nothing in flight and nothing newly ready.
                elif not in_flight and not self._ready_node_ids():
                    self.run.status = "error"
                    self.run.finished_at = time.time()
                    terminal = "error"
            if terminal is not None:
                _record_run_metric(self.run, terminal)
                return

            time.sleep(0.3)


class PlanRegistry:
    """Holds all PlanRuns in memory."""

    STASH_TTL_S = 600.0  # 10 minutes; hook stashes plans just before frontier consumes them.

    def __init__(self, plans_dir: Path):
        self.plans_dir = plans_dir
        self.runs: dict[str, PlanRun] = {}
        self.lock = threading.Lock()
        # stash_id -> (plan, expires_at). Populated by the UserPromptSubmit
        # hook so the frontier can trigger a pre-decomposed plan via
        # slm_run_stashed(stash_id) instead of re-emitting the whole DAG
        # as tool arguments. Entries are one-shot (removed on pop) so a
        # hostile session can't re-run the same plan twice.
        self.stashes: dict[str, tuple[Plan, float]] = {}
        self.stash_lock = threading.Lock()

    def stash(self, plan: Plan) -> str:
        stash_id = f"auto-{uuid.uuid4().hex[:12]}"
        now = time.time()
        with self.stash_lock:
            # Opportunistic sweep: cheap, keeps the dict bounded.
            expired = [k for k, (_, exp) in self.stashes.items() if exp <= now]
            for k in expired:
                del self.stashes[k]
            self.stashes[stash_id] = (plan, now + self.STASH_TTL_S)
        return stash_id

    def pop_stash(self, stash_id: str) -> Plan | None:
        now = time.time()
        with self.stash_lock:
            entry = self.stashes.pop(stash_id, None)
        if entry is None:
            return None
        plan, expires_at = entry
        if expires_at <= now:
            return None
        return plan

    def list_plan_files(self) -> list[str]:
        if not self.plans_dir.exists():
            return []
        return sorted(p.name for p in self.plans_dir.glob("*.json"))

    def load_from_file(self, name: str) -> Plan:
        path = self.plans_dir / name
        if not path.exists():
            raise PlanError(f"plan file not found: {name}")
        return Plan.from_file(path)

    def register(self, run: PlanRun) -> None:
        with self.lock:
            self.runs[run.run_id] = run

    def get(self, run_id: str) -> PlanRun | None:
        with self.lock:
            return self.runs.get(run_id)

    def list_runs(self) -> list[dict]:
        with self.lock:
            return [
                {
                    "run_id": r.run_id,
                    "plan_id": r.plan.plan_id,
                    "status": r.status,
                    "created_at": r.created_at,
                    "finished_at": r.finished_at,
                    "node_count": len(r.nodes),
                }
                for r in sorted(self.runs.values(), key=lambda x: -x.created_at)
            ]
